#!/bin/bash
# Setup PostgreSQL database for DeepSeek-OCR Medical Records
# This script creates the database, installs extensions, and applies schema

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "========================================"
echo "  DeepSeek-OCR Database Setup"
echo "========================================"
echo ""

# Check if PostgreSQL is installed
if ! command -v psql &> /dev/null; then
    echo -e "${RED}✗ PostgreSQL client (psql) not found${NC}"
    echo "Install PostgreSQL: https://www.postgresql.org/download/"
    exit 1
fi

echo -e "${GREEN}✓ PostgreSQL client found${NC}"

# Get database credentials
echo ""
echo "Database Configuration"
echo "----------------------"
read -p "PostgreSQL host [localhost]: " DB_HOST
DB_HOST=${DB_HOST:-localhost}

read -p "PostgreSQL port [5432]: " DB_PORT
DB_PORT=${DB_PORT:-5432}

read -p "Database name [medical_records]: " DB_NAME
DB_NAME=${DB_NAME:-medical_records}

read -p "PostgreSQL admin user [postgres]: " ADMIN_USER
ADMIN_USER=${ADMIN_USER:-postgres}

read -sp "PostgreSQL admin password: " ADMIN_PASSWORD
echo ""

read -p "Application database user [medical_app]: " APP_USER
APP_USER=${APP_USER:-medical_app}

read -sp "Application user password: " APP_PASSWORD
echo ""
echo ""

# Test connection
echo "Testing PostgreSQL connection..."
if PGPASSWORD="$ADMIN_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$ADMIN_USER" -d postgres -c "SELECT 1" > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Connection successful${NC}"
else
    echo -e "${RED}✗ Connection failed${NC}"
    echo "Please check your credentials and PostgreSQL server status"
    exit 1
fi

# Create database
echo ""
echo "Creating database..."
PGPASSWORD="$ADMIN_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$ADMIN_USER" -d postgres <<EOF
-- Create database if not exists
SELECT 'CREATE DATABASE $DB_NAME'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DB_NAME')\gexec

-- Create application user if not exists
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_user WHERE usename = '$APP_USER') THEN
        CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
    END IF;
END
\$\$;

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $APP_USER;
EOF

echo -e "${GREEN}✓ Database created${NC}"

# Install pgvector extension
echo ""
echo "Installing pgvector extension..."
PGPASSWORD="$ADMIN_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$ADMIN_USER" -d "$DB_NAME" <<EOF
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOF

echo -e "${GREEN}✓ Extensions installed${NC}"

# Apply schema
echo ""
echo "Applying schema..."
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PGPASSWORD="$ADMIN_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$ADMIN_USER" -d "$DB_NAME" -f "$SCRIPT_DIR/schema_v1.sql"

echo -e "${GREEN}✓ Schema applied${NC}"

# Grant permissions to application user
echo ""
echo "Setting permissions..."
PGPASSWORD="$ADMIN_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$ADMIN_USER" -d "$DB_NAME" <<EOF
GRANT CONNECT ON DATABASE $DB_NAME TO $APP_USER;
GRANT USAGE ON SCHEMA public TO $APP_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $APP_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $APP_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $APP_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $APP_USER;
EOF

echo -e "${GREEN}✓ Permissions set${NC}"

# Create .env file
echo ""
echo "Creating .env file..."
cat > "$SCRIPT_DIR/../.env" <<EOF
# PostgreSQL Database Configuration
# Generated by setup_database.sh on $(date)

DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USER=$APP_USER
DB_PASSWORD=$APP_PASSWORD
DB_POOL_SIZE=10
EOF

echo -e "${GREEN}✓ .env file created${NC}"

# Verify installation
echo ""
echo "Verifying installation..."
VERIFICATION_RESULT=$(PGPASSWORD="$APP_PASSWORD" psql -h "$DB_HOST" -p "$DB_PORT" -U "$APP_USER" -d "$DB_NAME" -t -c "
SELECT
    (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public') as tables,
    (SELECT COUNT(*) FROM information_schema.views WHERE table_schema = 'public') as views,
    (SELECT extname FROM pg_extension WHERE extname = 'vector') as pgvector
")

echo "Tables created: $(echo "$VERIFICATION_RESULT" | awk '{print $1}')"
echo "Views created: $(echo "$VERIFICATION_RESULT" | awk '{print $3}')"
echo "pgvector extension: $(echo "$VERIFICATION_RESULT" | awk '{print $5}')"

# Success
echo ""
echo "========================================"
echo -e "${GREEN}✓ Database setup complete!${NC}"
echo "========================================"
echo ""
echo "Connection string:"
echo "  postgresql://$APP_USER:***@$DB_HOST:$DB_PORT/$DB_NAME"
echo ""
echo "Environment variables saved to: .env"
echo ""
echo "Next steps:"
echo "  1. Load environment variables: source .env"
echo "  2. Install Python dependencies: pip install psycopg2-binary transformers"
echo "  3. Test connection: python -c \"from backend.db_connector import DatabaseConnector; DatabaseConnector().test_connection()\""
echo "  4. Run batch processing with database: python batch_process.py --input ./docs --output ./processed"
echo ""
